---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: weather-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 158668600410.dkr.ecr.ap-southeast-1.amazonaws.com/mob-app:backend-1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      tolerations:
      - key: "eks.amazonaws.com/compute-type"
        operator: "Equal"
        value: "fargate"
        effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: weather-app
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: backend
