---
apiVersion: v1
kind: Namespace
metadata:
  name: weather-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 158668600410.dkr.ecr.ap-southeast-1.amazonaws.com/mob-app:frontend-1.0  # Frontend image URI
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: "http://backend-service.weather-app.svc.cluster.local:5000"  # URL to connect frontend with backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: weather-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: weather-app
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 3000
